@startuml
left to right direction
skinparam usecase {
  BackgroundColor LightSkyBlue
}
    actor 前台 as reception
    rectangle  羽毛球拍售后管理模块用况分析{
        actor 修理 as repair    

        usecase 申请退货退款 as a1
        usecase 处理退货退款申请 as a2
        usecase 申请保修  as a3
        usecase  保修任务分配  as a4
        usecase  退货退款管理  as s1
        usecase  保修管理  as s2
        usecase  员工KPI管理  as s3
        usecase 返厂保修 as b1
        usecase 店内保修 as b2
        usecase 库存数更新 as b3
    }

    guest->reception
    reception->a1
    reception->a2
    reception->a3
    repair->a4
    repair->b2
    reception->b3
    
    a1 ...> s1:<<include>>
    a2 ...> s1:<<include>>
    a3 ...> s2:<<include>>
    a4 ...> s2:<<include>>
    s3 ...> a2:<<extends>>
    s3 ...> a4:<<extends>>


    b1 ..> s2:<<extends>>
    b2 ...> s2:<<extends>>

    note "当退货退款任务完成时, 扩展KPI计算" as note1
    (a2) .. note1
    note "当保修任务完成时, 扩展KPI计算" as note2
    (a4) .. note2
    note "损坏程度低，扩展店内维修" as note3
    (s2) .. note3
    note "损坏程度高，扩展返厂维修" as note4
    (s2) .. note4


@enduml